### ISSUE TITLE
Hello, question about NCLT groundtruth.

### ISSUE THREAD

**Issue by hr2894235132** [Taeyoung96/FAST_LIO_ROS2#8]
Hello, I see that you have also encountered the problem that the groundtruth format downloaded from the NCLT official website is not the same as the tum format, and i can't use evo to evaluate, I want to ask if you solved it?

**Comment by Taeyoung96** [comment]
@hr2894235132   
Hi, I solved the problem by converting the data from the NCLT to a bagfile.   
I utilized the `/gt` topic to evaluate the trajectory using the bag format as input to evo instead of the tum format.  

The repo below helped me convert the raw data from NCLT into a ros bagfile.  
https://github.com/HaisenbergPeng/ROLL/tree/main/scripts  
https://github.com/bierschi/nclt2ros

**Comment by hr2894235132** [comment]
> @hr2894235132 Hi, I solved the problem by converting the data from the NCLT to a bagfile. I utilized the `/gt` topic to evaluate the trajectory using the bag format as input to evo instead of the tum format.
> 
> The repo below helped me convert the raw data from NCLT into a ros bagfile. https://github.com/HaisenbergPeng/ROLL/tree/main/scripts https://github.com/bierschi/nclt2ros

thanks a lot！best wishes！
